jump_to_flask/myproject/pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import AnswerForm
from pybo.models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
# 답변 등록은 POST요청만 있으므로 GET, POST 분기처리는 필요없다.
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now())
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))

    # content = request.form['content']                                # POST 폼 방식으로 전송된 데이터 항목 중 name 속성이 content인 값을 의미
    # answer = Answer(content=content, create_date=datetime.now())
    # question.answer_set.append(answer)                               # "질문에 달린 답변들"을 의미
    # db.session.commit()
    # return redirect(url_for('question.detail', question_id=question_id))

    return render_template('question/question_detail.html', question=question, form=form)

# @bp.route의 methods 속성에는 'POST'를 지정했다. 
# 답변을 저장하는 질문 상세 템플릿의 form 엘리먼트가 POST 방식이므로 같은 값을 지정해야 한다. 
# 만약 @bp.route에 똑같은 폼 방식을 지정하지 않으면 오류가 발생하므로 주의하자.


    # answer = Answer(question=question, content=content, create_date=datetime.now())
    # db.session.add(answer)
    # 이런 식으로 답변을 저장할수도 있다

jump_to_flask/myproject/pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm          # forms.py에서 만든 QuestionsForm 클래스를 import한다

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form) 

# question_list.html에서 만들어진 질문 등록 버튼에 연동
@bp.route('/create/', methods=('GET', 'POST'))  # question_form.html에서 질문 등록 버튼의 method는 post 방식을 사용한다 그러므로 get과 post 방식을 모두 처리할 수 있게 해준다
def create():
    form = QuestionForm()
    # question_form.html 템플릿에 전달하는 QuestionForm의 객체(form)는 템플릿에서 라벨이나 입력폼 등을 만들때 필요하다.
    # question_form.html을 만들어야한다

    # 이후 템플릿에 전송한 폼 데이터를 저장하는 코드를 작성해야한다(if 구문 추가)
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    # if 문의 request.method는 create 함수로 요청된 전송 방식을 의미
    # form.validate_on_submit 함수는 전송된 폼 데이터의 정합성을 점검
    # 즉, QuestionForm 클래스의 각 속성에 지정한 DataRequired() 같은 점검 항목에 이상이 없는지 확인한다

    # 즉, 위 코드에 추가한 내용(if 문)은 POST 요청이고 폼 데이터에 이상이 없을 경우 질문을 저장한 뒤 main.index 페이지로 이동하라는 내용

    # 코드를 보면 폼으로부터 전달받은 "제목"에 해당하는 데이터는 form.subject.data로 얻고 있다. form.content.data도 마찬가지이다.

    # 코드의 핵심은 데이터 전송 방식이 POST인지 GET인지에 따라서 달리 처리하는 부분이다.
    # 질문 목록에서 <질문 등록하기> 버튼을 누르거나 질문 등록 화면에서 <저장하기> 버튼을 누르면 똑같이 localhost:5000/question/create/ 페이지를 요청하므로 create 함수가 이 요청을 받는다
    # 다만 create 함수에서 요청 방식을 구분해서 처리한다
    # 즉, <질문 등록하기> 버튼을 누르는 것은 GET 방식 요청이므로 질문 등록 화면을 보여 주고
    # <저장하기>버튼을 누르면 POST 방식 요청이므로 데이터베이스에 질문을 저장한다.

    # 그런데 여기까지 작성하고 <저장하기> 버튼을 눌러도 제대로 동작하지 않는다.(CSRF 문제를 해결해야 저장이 가능하다)
    
    return render_template('question/question_form.html', form=form)

jump_to_flask/myproject/pybo/templates/question/question_detail.html
<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>

<!-- 답변표시하기 -->
<h5>{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
<!-- 템플릿 필터는 | 문자 뒤에 추가해서 사용한다 -->
<!-- 템플릿 내장 필터 https://jinja.palletsprojects.com/en/2.11.x/templates/#builtin-filters -->
<div>
    <ul>
    {% for answer in question.answer_set %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>

<!-- 답변등록 버튼 만들기 -->
<form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">

    <!-- CSRF 코드와 오류 표시 기능 추가 -->
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items() %}
        <strong>{{ form[field].label }}</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->

    <div class="mb-3">
        <textarea name="content" id="content" rows="15"></textarea>
    </div>
    
    <input type="submit" value="답변등록">
</form>

<!-- question.subject와 question.content의 question은 render_template 함수에 전달한 질문 객체 -->

jump_to_flask/myproject/pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}                          <!-- CSRF 토큰 오류에서 탈출 -->

         <!-- 오류표시 Start -->
         {% if form.errors %}
         <div class="alert alert-danger" role="alert">
             {% for field, errors in form.errors.items() %}
             <strong>{{ form[field].label }}</strong>
             <ul>
                 {% for error in errors %}
                 <li>{{ error }}</li>
                 {% endfor %}
             </ul>
             {% endfor %}
         </div>
         {% endif %}
         <!-- 오류표시 End -->


        <!-- 이런 방식은 폼을 빠르게 만드느 데는 도움이 되지만 내가 원하는 디자인을 적용하기 어렵다
        -------

        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}      템플릿 코드에서 부트스트랩을 사용하기 위해서는 (class="")을 사용한다

        {{ form.content.label }}
        {{ form.content(class="form-control") }}

        ------- -->

        <!-- 내가 원하는 방식으로 디자인하기 위해서는 이런 식으로 작성한다 -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
            <!-- subject 필드의 value값으로 form.subject.data or ''를 입력하면 이미 전송한 데이터가 다시 설정된다. -->
            <!-- 여기서 or ''은 "현재 템플릿이 GET 방식으로 요청되는 경우 기존 입력값이 없으므로(None으로 출력) 이를 방지하기 위해서" 사용 -->
            <!-- 즉, 이렇게 하면 form.subject.data에 값이 없을 때 None이 아니라 ''이 출력된다 -->
            <!-- 이 방식을 사용한다면 오류가 뜨더라도 이전까지 작성했던 내용이 사라지지 않는다 -->
        </div>

        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

<!-- "CSRF Token" 오류는 무엇일까?  -->
<!-- CSRF는 보안 관련 항목으로, form 엘리먼트를 통해 전송된 데이터가 실제 웹 사이트에서
     만들어진 데이터인지 검증하는 데 필요한 CSRF 토큰이 빠졌다는 의미 -->


     

jump_to_flask/myproject/pybo/templates/question/question_list.html
<!-- 질문 목록 -->   <!-- 템플릿 태그. 이 태그가 파이썬 코드와 연결된다 -->
{% if question_list %}            <!-- render_template 함수에서 전달받은 질문 목록 데이터 question_list가 있는지 검사 -->
    <ul>
    {% for question in question_list %}             <!-- question_list에 저장된 데이터를 하나씩 꺼내 question 객체에 대입 (for 문))-->       
        <li><a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a></li>      <!-- for 문에서 얻은 question 객체의 id를 출력 -->
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}                      